export const actions = {
  ADD_ITEM: "ADD_ITEM",
  CLEAR_CART: "CLEAR_CART",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  HIDE_MODAL: "HIDE_MODAL",
};
